package com.example.composeapplication

/*
 What Is a Test?
A test is a manual or automatic procedure used to evaluate if the System Under
Test (SUT) behaves correctly.
The SUT may be a method, an entire class, a module or even a whole application.

Regression:
After adding new functionality or feature, another feature where use to work fine, is broken.

What we should test?
Testing logic of application should be the main goal, but we should write tests
 for code that breaks or will change often.

And what we shouldn't test?
External dependencies and Autogenerated code


TDD:
TDD is a process in which you write the tests for the code you are going to add or
modify before you write the actual code.


False positive:
This happens when you have a test that is passing but really shouldn't be.


Unit tests :
Unit tests are the quickest, easiest to write and cheapest to run. They generally test
one outcome of one method at a time. They are independent of the Android framework.


Robolectric:
Simulates the Android runtime, it allows you to test code that depends
on the framework without using a device or emulator.


Integration tests:
It tests how things work together.

UI tests:
The tests on this layer check if the UI of your application works correctly.

UI Automator:
Google recommends it only when you have to do cross-app functional UI testing
across system and installed apps.


 */
